/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
Ans: 4613732*/ 

#include<stdio.h>
void main()
{
    int fibonacci1,fibonacci2,fibonacci3=0,a;
    fibonacci1=-1;
    fibonacci2=1;
    while(fibonacci3<=4000000)
    {
        fibonacci1=fibonacci2;
        fibonacci2=fibonacci3;
        fibonacci3=fibonacci1+fibonacci2;


    if(fibonacci3%2==0)
    {
        a=a+fibonacci3;
    }
 }printf("fibonacci is:%d\n",fibonacci3);   
 printf("sum of even valued terms:%d\n",a);
}
